name: Automated Code Review with AWS Bedrock

on:
  push:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install boto3

      # Step 4: Run code review with AWS Bedrock
      - name: Review code using AWS Bedrock
        env:
          AWS_ACCESS_KEY_ID: ${{ AKIAQEFWA3IPEJBIVRB6 }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}
          AWS_REGION: ${{ us-east-1 }}
        run: |
          python review_code.py

      # Step 5: Commit and push corrections back to the repo
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated code corrections by AWS Bedrock"
          git push
